FROM mysql:8.0

ENV MYSQL_DATABASE=db_hunian_mahmudah
ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes

EXPOSE 3306

CMD ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
